name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4, 8.0, 8.1]
        laravel: [8.*, 9.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 8.*
            testbench: 6.*

          - laravel: 9.*
            testbench: 7.*

        exclude:
          # Laravel 8.0 has type incompatibilities with PHP 8.1.
          - laravel: 8.*
            php: 8.1
            dependency-version: prefer-lowest

          # Laravel 9 requires PHP 8.0.
          - laravel: 9.*
            php: 7.3

          - laravel: 9.*
            php: 7.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    services:
      singlestore:
        # check for new versions at https://github.com/singlestore-labs/singlestoredb-dev-image/pkgs/container/singlestoredb-dev/versions
        image: ghcr.io/singlestore-labs/singlestoredb-dev:0.1.3
        ports:
          - "3306:3306"
        env:
          # this license key is only authorized for use in SingleStore laravel tests and is heavily restricted
          # if you want a free SingleStore license for your own use please visit https://www.singlestore.com/cloud-trial/
          SINGLESTORE_LICENSE: BGIxODZiYTg1YWUxYjRlODRhYzRjMGFmYTA1OTkxYzgyAAAAAAAAAAABAAAAAAAAACgwNQIZANx4NIXJ7CWvKYYb3wIyRXxBY7fdAnLeSwIYLy2Q0jA124GAkl04yuGrD59Zpv85DVYXAA==
          ROOT_PASSWORD: "test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer self-update
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute Unit Tests
        run: vendor/bin/phpunit

      - name: SingleStore Container Logs
        run: docker logs $(docker ps -ql)

      - name: Create Test Database
        run: |
          mysql -h 127.0.0.1 -u root -ptest -e "create database test"

      - name: Execute Integration Tests
        run: vendor/bin/phpunit
        env:
          HYBRID_INTEGRATION: 1
          DB_DATABASE: test
          DB_USERNAME: root
          DB_PASSWORD: test
          DB_HOST: 127.0.0.1
